### ISSUE TITLE
Custom end state

### ISSUE THREAD

**Issue by cmboling** [github/codescanning-jira-integration#6]
Not all Jira issues use the "Done" state when an issue/severity alert is closed. Some use a custom state, such as "Closed". Provide a custom flag that will support this.

**Comment by zbazztian** [comment]
Makes sense. Note that, in theory, this should be straightforward, since we already have the constant [CLOSED_STATUS](https://github.com/github/codescanning-jira-integration/blob/master/jiralib.py#L11). If we do this, it might also be necessary to have switches for [custom transitions](https://github.com/github/codescanning-jira-integration/blob/master/jiralib.py#L10).
